language: generic
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=06e3e394f41bd389a11ce51a2bb4ec46ff082e86d25f4f90644aad5b4faaf0f1
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=1bc9988993ee84bc814e5a7f33cc90f670a19f6a
    - TARGETHOST=aarch64-linux-android
    - BITS=64
    - REPONAME=bitcoin
    - RENAME=bitcoin
    - CONFIGURE=--disable-man
  matrix:
    - unused=true
    - TARGETHOST=armv7a-linux-androideabi BITS=32
    - TARGETHOST=x86_64-linux-android
    - TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=f8d8a318e8ff7fb396b3102a532c790a7430ed81
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=f8d8a318e8ff7fb396b3102a532c790a7430ed81
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=f8d8a318e8ff7fb396b3102a532c790a7430ed81
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=f8d8a318e8ff7fb396b3102a532c790a7430ed81
    - REPO=https://github.com/elementsproject/elements.git COMMIT=c53a31363290a5470b039bf3548d0cadba1926e0 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=c53a31363290a5470b039bf3548d0cadba1926e0 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/elementsproject/elements.git COMMIT=c53a31363290a5470b039bf3548d0cadba1926e0 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=c53a31363290a5470b039bf3548d0cadba1926e0 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $REPONAME $RENAME $CONFIGURE $TARGETHOST $BITS"
