language: generic
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=6603364284e4fe27f973e6d2e42b7eacf418baabf87b89638d46453772652d2e
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=2472733a24a9364e4c6233ccd04166a26a68cc65
    - TARGETHOST=aarch64-linux-android
    - BITS=64
    - REPONAME=bitcoin
    - RENAME=bitcoin
    - CONFIGURE=--disable-man
  matrix:
    - unused=true
    - TARGETHOST=armv7a-linux-androideabi BITS=32
    - TARGETHOST=x86_64-linux-android
    - TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - REPO=https://github.com/elementsproject/elements.git COMMIT=551483eae50ff2ee48ed17d6b22bb1a26284b635 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=551483eae50ff2ee48ed17d6b22bb1a26284b635 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/elementsproject/elements.git COMMIT=551483eae50ff2ee48ed17d6b22bb1a26284b635 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=551483eae50ff2ee48ed17d6b22bb1a26284b635 REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $REPONAME $RENAME $CONFIGURE $TARGETHOST $BITS"
