language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=41790e5797c2b1977894281ee577551f6855a54ec5923ad2018456f2046470c7
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=3e4829af097b12f4255e9b04fa27c408850a783f
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
    - BITS=64
  matrix:
    - UNUSED=true
    - TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32
    - TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST $BITS"
